apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsbridge
  labels:
    app: smsbridge

spec:
  replicas: 1

  selector:
    matchLabels:
      app: smsbridge

  template:
    metadata:
      labels:
        app: smsbridge

    spec:
      containers:
        - name: smsbridge
          image: tharunm11/smsbridge:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: smsbridge-secret
                  key: GATEWAY_URL

            - name: GATEWAY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: smsbridge-secret
                  key: GATEWAY_TOKEN

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: smsbridge-secret
                  key: API_KEY

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"