apiVersion: v1
kind: Service
metadata:
  name: smsbridge
spec:
  type: NodePort
  selector:
    app: smsbridge
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080